-- Clean the slate completely to establish our high-performance table blueprint
DROP TABLE IF EXISTS ofa_upload;

CREATE TABLE ofa_upload (
    -- ==========================================
    -- 0. SYSTEM DATA METRICS AUTOMATION ENGINES (DO NOT TOUCH)
    -- ==========================================
    id SERIAL PRIMARY KEY,
    "file_attachment" TEXT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- ==========================================
    -- 1. CORE DATA & MATERIAL PROFILES (1 - 35)
    -- ==========================================
    "TagNo" TEXT NULL,
    "Item Name" TEXT NULL,
    "Quantity" NUMERIC DEFAULT 0,
    "Project" TEXT NULL,
    "Plate MATERIAL" TEXT NULL,
    "Flange MATERIAL" TEXT NULL,
    "Flange Type" TEXT NULL,
    "Piece Type" TEXT NULL,
    "Weld Type" TEXT NULL,
    "Holder Type" TEXT NULL,
    "Line_Size" TEXT NULL,
    "Size in NPS OR DN" TEXT NULL,
    "Flange Schedule" TEXT NULL,
    "Pipe Wall Thk" TEXT NULL,
    "Rating" TEXT NULL,
    "RJ HOLDER MATERIAL" TEXT NULL,
    "Drain/Vent" TEXT NULL,
    "Smooth Finish" TEXT NULL,
    "Serration" TEXT NULL,
    "Stellite" TEXT NULL,
    "Fluid/Service_Name" TEXT NULL,
    "Service Discription" TEXT NULL,
    "Service Type" TEXT NULL,
    "Calculation Standard" TEXT NULL,
    "Flow Element Type" TEXT NULL,
    "Flow Rate Unit" TEXT NULL,
    "Flow Rate Minimum" NUMERIC DEFAULT 0,
    "Flow Rate Maximum" NUMERIC DEFAULT 0,
    "Flow Rate Normal" NUMERIC DEFAULT 0,
    "Flow Rate at FullScale" NUMERIC DEFAULT 0,
    "Tapping" TEXT NULL,
    "Multi Hole" TEXT NULL,
    "Pipe Material" TEXT NULL,
    "Pressure Unit" TEXT NULL,
    "Temp Unit" TEXT NULL,

    -- ==========================================
    -- 2. GAS DIAGNOSTICS & RATINGS (36 - 70)
    -- ==========================================
    "Viscosity Unit" TEXT NULL,
    "Density Unit" TEXT NULL,
    "Density_Calc_Method" TEXT NULL,
    "MolecularWeight_Customer" NUMERIC DEFAULT 0,
    "Compressibilty_atFlow_Customer" NUMERIC DEFAULT 0,
    "Compressibilty_atBase_Customer" NUMERIC DEFAULT 0,
    "Gas Name" TEXT NULL,
    "Base Pressure" TEXT NULL,
    "Upstream Pressure" TEXT NULL,
    "Base_Temperature" TEXT NULL,
    "Operating_Temperature" TEXT NULL,
    "Vapour_Pressure" TEXT NULL,
    "Density_at_Base_Customer" NUMERIC DEFAULT 0,
    "Density_at_Flow_Customer" NUMERIC DEFAULT 0,
    "Viscosity_Customer" NUMERIC DEFAULT 0,
    "IsentropicExponenet_Customer" NUMERIC DEFAULT 0,
    "DP Unit" TEXT NULL,
    "DP at Full Scale" NUMERIC DEFAULT 0,
    "Design Pressure Discription" TEXT NULL,
    "Design Pressure" NUMERIC DEFAULT 0,
    "Design Temp Discription" TEXT NULL,
    "Design Temp" TEXT NULL,
    "Flange Standard" TEXT NULL,
    "Plate Thk Customer" TEXT NULL,
    "Spare Plate Required" TEXT NULL,
    "Stud/Nut" TEXT NULL,
    "Gasket" TEXT NULL,
    "JackBolt" TEXT NULL,
    "Packing_Cost_Manual" NUMERIC DEFAULT 0,
    "Accessories" TEXT NULL,
    "Accessories_Amt" NUMERIC DEFAULT 0,
    "IBR" TEXT NULL,
    "IBR_Amt_Manual" NUMERIC DEFAULT 0,
    "Nace" TEXT NULL,
    "Nace_Type" TEXT NULL,

    -- ==========================================
    -- 3. COMMERCIAL TESTING & GEOMETRIES (71 - 105)
    -- ==========================================
    "Nace_Percent" NUMERIC DEFAULT 0,
    "Calibration" TEXT NULL,
    "CalibrationAmt_Manual" NUMERIC DEFAULT 0,
    "Freight_Required" TEXT NULL,
    "Freight_Amt_Manual" NUMERIC DEFAULT 0,
    "Special_Requirement" TEXT NULL,
    "Special_Requirement_Amt" NUMERIC DEFAULT 0,
    "OFA Tap Orientation" TEXT NULL,
    "FNA Tap Orientation" TEXT NULL,
    "Venturi Tap Orientation" TEXT NULL,
    "Plug_Material" TEXT NULL,
    "Pressure_Tap_Angle" TEXT NULL,
    "JackBolt_Position" TEXT NULL,
    "ItemCode_Heading" TEXT NULL,
    "ItemCode" TEXT NULL,
    "TestSchedule" TEXT NULL,
    "FNA Pipe Machining Required" TEXT NULL,
    "FNA Pipe Machined Cost" NUMERIC DEFAULT 0,
    "FNA Total Assy. Length" TEXT NULL, -- Clean unified column token representation
    "FNA Upstream Length" TEXT NULL,
    "FNA Pipe Length Show to Customer" TEXT NULL,
    "FNA Pipe Length Customer" TEXT NULL,
    "Chamfer" TEXT NULL,
    "ØD1" TEXT NULL,                     -- Clean mathematical character validation
    "Adapter Rating" TEXT NULL,
    "Flow Nozzle Holding Ring Material" TEXT NULL,
    "Flow Nozzle Material" TEXT NULL,
    "Nipple Material" TEXT NULL,
    "Nipple Size" TEXT NULL,
    "Nipple Schedule" TEXT NULL,
    "Nipple Quantity" NUMERIC DEFAULT 0,
    "Venturi Throat Material" TEXT NULL,
    "Cyllinder Material" TEXT NULL,
    "Cone Material" TEXT NULL,
    "Piezometer Ring Material" TEXT NULL,

    -- ==========================================
    -- 4. TAPPING SYSTEMS & STRUCTURAL GEOMETRIES (106 - 126)
    -- ==========================================
    "End Flange Standard" TEXT NULL,
    "End Flange Type" TEXT NULL,
    "End Flange Material" TEXT NULL,
    "End Flange Rating" TEXT NULL,
    "No of End Flange" NUMERIC DEFAULT 0,
    "Adapter Material" TEXT NULL,
    "No. of Tapping 1" NUMERIC DEFAULT 0,
    "Tap Size 1" TEXT NULL,
    "No. of Tapping 2" NUMERIC DEFAULT 0,
    "Tap Size 2" TEXT NULL,
    "Companion Flange Required" TEXT NULL,
    "Tapping Flange" TEXT NULL,
    "Tapping Flange Size" TEXT NULL,
    "PitotTube Type" TEXT NULL,
    "Duct Inside Width" TEXT NULL,
    "Duct Outside Width" TEXT NULL,
    "Duct Inside Height" TEXT NULL,
    "Duct Outside Height" TEXT NULL,
    "PitotTube Probe Material" TEXT NULL,
    "Pitot Tube Type" TEXT NULL,
    "Pitot End Support" TEXT NULL,
    "Clamping Condition" TEXT NULL,
    "Pitot Tube End Connection Material" TEXT NULL,
    "Pitot Tube Sleeve Material / tag_number" TEXT NULL
);